<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	</PropertyGroup>
	<!-- <ItemGroup>
	  <None Remove="Phi-3-mini-4k-instruct-q4.gguf" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Phi-3-mini-4k-instruct-q4.gguf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup> -->

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.12" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="LLamaSharp" Version="0.26.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.26.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DocMind.Core\DocMind.Core.csproj" />
		<ProjectReference Include="..\DocMind.Data\DocMind.Data.csproj" />
		<ProjectReference Include="..\DocMind.Infrastructure\DocMind.Infrastructure.csproj" />
		<ProjectReference Include="..\DocMind.Services\DocMind.Services.csproj" />
	</ItemGroup>
</Project>